hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name="index"),
    path("brian",views.brian,name="brian"),
    path("<str:name>", views.greet,name="greet"),
    path("david",views.david,name="david"),
]

lecture3/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name="index"),
]

tasks/urls.py
from django.urls import path
from . import views
app_name = "Tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add/",views.add,name="add")
]

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("hello,brian")

def david(request):
    return HttpResponse("Hello,David")

def greet(request,name):
    return render(request,"hello/greet.html",{
       "name": name.capitalize() 
    })

newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request, "newyear/index.html",{
        
        'newyear': now.month == 1 and now.day == 1 
    })

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

class NewTaskForm(forms.Form):
    task= forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority",min_value=1,max_value=5)
# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    return render(request, "tasks/index.html",{
        'tasks': request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task=form.cleaned_data["task"]
            request.session["tasks"]+=[task]
            request.session.modified = True
            return  HttpResponseRedirect(reverse("Tasks:index"))
        else:
            return render(request, "tasks/add.html",{
                "form": form})
    return render(request, "tasks/add.html",{
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang= "en">
    <head>
        <title>hello!</title>
    </head>
    <body>
        <h1>hello,{{name}}!</h1>

    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>hello!</title>
        
    </head>
    <body>
        <h2>hello,world!</h2>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> is it newyear?</title>
        <link href="{%static 'newyear/styles.css'%}" rel="stylesheet">
    </head>
    <body>
        {%if newyear%}
        <h1> IT IS NEW YEAR</h1>
        {%else%}
        <h1> IT IS NOT NEW YEAR</h1>
        {%endif%}
    </body>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
        <h1> Add Tasks</h1>
       <form action="{% url 'Tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add Task">
         </form>
         <a href="{% url 'Tasks:index' %}">Back</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
        <ul>
            {% for task in tasks %}
            <li>{{ task }}</li>
            {%empty%}
            <li>No tasks.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'Tasks:add' %}">Add Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">    
    <head>
        <title>Tasks</title>
        <link href="{%static 'tasks/styles.css'%}" rel="stylesheet">
    </head>
    <body>
    {% block body %}
    {% endblock %}
    </body>
</html>